version: '3'

services:
  sjakk-arena:
    container_name: sjakk-arena
    image: sjakk-arena
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
